services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: carsharing-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "CarSharing_2026!"
    ports:
      - "1433:1433"
    volumes:
      - carsharing-sqlserver-data:/var/opt/mssql
  rabbitmq:
    image: rabbitmq:3-management
    container_name: carsharing-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

volumes:
  carsharing-sqlserver-data:
